from db_sql import Database  # ← Esto es una importación absoluta

def create_tables(db):
    """
    Create the necessary tables in the database.
    This function will be called from main.py.
    """
    # Create tickers table (tickers)
    create_stock_data = """
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tickers')
        BEGIN
            CREATE TABLE tickers (
                symbol NVARCHAR(20) NOT NULL,   
                source NVARCHAR(50),
                ingest_date DATE,    
                CONSTRAINT pk_tickers PRIMARY KEY (symbol)  
            );
        END;
    """
    db.execute_non_query(create_stock_data)

    # Create table (CompanyInfo)
    create_company_info = """
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'company_info')
        BEGIN
            CREATE TABLE company_info (
                date DATE NOT NULL,
                address1 NVARCHAR(255),
                address2 NVARCHAR(255),
                ask FLOAT,
                asksize INT,
                auditrisk INT,
                averageanalystrating NVARCHAR(50),
                averagedailyvolume10day BIGINT,
                averagedailyvolume3month BIGINT,
                averagevolume BIGINT,
                averagevolume10days BIGINT,
                beta FLOAT,
                beta3year FLOAT,
                bid FLOAT,
                bidsize INT,
                boardrisk INT,
                bookvalue FLOAT,
                category NVARCHAR(100),
                city NVARCHAR(100),
                companyofficers NVARCHAR(MAX),
                compensationasofepochdate BIGINT,
                compensationrisk INT,
                corporateactions NVARCHAR(MAX),
                country NVARCHAR(100),
                cryptotradeable BIT,
                currency NVARCHAR(10),
                currentprice FLOAT,
                currentratio FLOAT,
                custompricealertconfidence NVARCHAR(50),
                dateshortinterest BIGINT,
                dayhigh FLOAT,
                daylow FLOAT,
                debttoequity FLOAT,
                displayname NVARCHAR(255),
                dividenddate BIGINT,
                dividendrate FLOAT,
                dividendyield FLOAT,
                earningscalltimestampend BIGINT,
                earningscalltimestampstart BIGINT,
                earningsgrowth FLOAT,
                earningsquarterlygrowth FLOAT,
                earningstimestamp BIGINT,
                earningstimestampend BIGINT,
                earningstimestampstart BIGINT,
                ebitda FLOAT,
                ebitdamargins FLOAT,
                enterprisetoebitda FLOAT,
                enterprisetorevenue FLOAT,
                enterprisevalue FLOAT,
                epscurrentyear FLOAT,
                epsforward FLOAT,
                epstrailingtwelvemonths FLOAT,
                esgpopulated BIT,
                exchange NVARCHAR(50),
                exchangedatadelayedby NVARCHAR(50),
                exchangetimezonename NVARCHAR(50),
                exchangetimezoneshortname NVARCHAR(10),
                exchangetransferdate NVARCHAR(50),
                exdividenddate NVARCHAR(50),
                executiveteam NVARCHAR(MAX),
                fax NVARCHAR(50),
                fiftydayaverage FLOAT,
                fiftydayaveragechange FLOAT,
                fiftydayaveragechangepercent FLOAT,
                fiftytwoweekchangepercent FLOAT,
                fiftytwoweekhigh FLOAT,
                fiftytwoweekhighchange FLOAT,
                fiftytwoweekhighchangepercent FLOAT,
                fiftytwoweeklow FLOAT,
                fiftytwoweeklowchange FLOAT,
                fiftytwoweeklowchangepercent FLOAT,
                fiftytwoweekrange NVARCHAR(50),
                financialcurrency NVARCHAR(10),
                firsttradedatemilliseconds BIGINT,
                fiveyearaveragereturn FLOAT,
                fiveyearavgdividendyield FLOAT,
                floatshares BIGINT,
                forwardeps FLOAT,
                forwardpe FLOAT,
                freecashflow FLOAT,
                fullexchangename NVARCHAR(255),
                fulltimeemployees INT,
                fundfamily NVARCHAR(100),
                fundinceptiondate BIGINT,
                gmtoffsetmilliseconds BIGINT,
                governanceepochdate BIGINT,
                grossmargins FLOAT,
                grossprofits FLOAT,
                hasprepostmarketdata BIT,
                heldpercentinsiders FLOAT,
                heldpercentinstitutions FLOAT,
                impliedsharesoutstanding BIGINT,
                industry NVARCHAR(255),
                industrydisp NVARCHAR(255),
                industrykey NVARCHAR(255),
                industrysymbol NVARCHAR(50),
                ipoexpecteddate NVARCHAR(50),
                irwebsite NVARCHAR(255),
                isearningsdateestimate BIT,
                language NVARCHAR(10),
                lastdividenddate BIGINT,
                lastdividendvalue FLOAT,
                lastfiscalyearend BIGINT,
                lastsplitdate BIGINT,
                lastsplitfactor NVARCHAR(50),
                legaltype NVARCHAR(100),
                longbusinesssummary NVARCHAR(MAX),
                longname NVARCHAR(255),
                market NVARCHAR(50),
                marketcap BIGINT,
                marketstate NVARCHAR(50),
                maxage INT,
                messageboardid NVARCHAR(100),
                mostrecentquarter BIGINT,
                namechangedate DATE,
                navprice FLOAT,
                netassets FLOAT,
                netexpenseratio FLOAT,
                netincometocommon FLOAT,
                nextfiscalyearend BIGINT,
                numberofanalystopinions INT,
                open_v FLOAT,
                operatingcashflow FLOAT,
                operatingmargins FLOAT,
                overallrisk INT,
                payoutratio FLOAT,
                phone NVARCHAR(50),
                postmarketchange FLOAT,
                postmarketchangepercent FLOAT,
                postmarketprice FLOAT,
                postmarkettime BIGINT,
                prevexchange NVARCHAR(50),
                previousclose FLOAT,
                prevname NVARCHAR(255),
                prevticker NVARCHAR(50),
                priceepscurrentyear FLOAT,
                pricehint INT,
                pricetobook FLOAT,
                pricetosalestrailing12months FLOAT,
                profitmargins FLOAT,
                quickratio FLOAT,
                quotesourcename NVARCHAR(255),
                quotetype NVARCHAR(50),
                recommendationkey NVARCHAR(50),
                recommendationmean FLOAT,
                region NVARCHAR(50),
                regularmarketchange FLOAT,
                regularmarketchangepercent FLOAT,
                regularmarketdayhigh FLOAT,
                regularmarketdaylow FLOAT,
                regularmarketdayrange NVARCHAR(50),
                regularmarketopen FLOAT,
                regularmarketpreviousclose FLOAT,
                regularmarketprice FLOAT,
                regularmarkettime BIGINT,
                regularmarketvolume BIGINT,
                returnonassets FLOAT,
                returnonequity FLOAT,
                revenuegrowth FLOAT,
                revenuepershare FLOAT,
                sandp52weekchange FLOAT,
                sector NVARCHAR(100),
                sectordisp NVARCHAR(100),
                sectorkey NVARCHAR(100),
                shareholderrightsrisk INT,
                sharesoutstanding BIGINT,
                sharespercentsharesout FLOAT,
                sharesshort BIGINT,
                sharesshortpreviousmonthdate BIGINT,
                sharesshortpriormonth BIGINT,
                shortname NVARCHAR(255),
                shortpercentoffloat FLOAT,
                shortratio FLOAT,
                sourceinterval BIGINT,
                state NVARCHAR(50),
                symbol NVARCHAR(20) NOT NULL,
                targethighprice FLOAT,
                targetlowprice FLOAT,
                targetmeanprice FLOAT,
                targetmedianprice FLOAT,
                threeyearaveragereturn FLOAT,
                tickerchangedate BIGINT,
                totalassets FLOAT,
                totalcash FLOAT,
                totalcashpershare FLOAT,
                totaldebt FLOAT,
                totalrevenue FLOAT,
                tradeable BIT,
                trailingannualdividendrate FLOAT,
                trailingannualdividendyield FLOAT,
                trailingeps FLOAT,
                trailingpe NVARCHAR(20),
                trailingpegratio FLOAT,
                trailingthreemonthnavreturns FLOAT,
                trailingthreemonthreturns FLOAT,
                triggerable BIT,
                twohundreddayaverage FLOAT,
                twohundreddayaveragechange FLOAT,
                twohundreddayaveragechangepercent FLOAT,
                typedisp NVARCHAR(50),
                volume BIGINT,
                website NVARCHAR(255),
                week52change FLOAT,
                yield FLOAT,
                ytdreturn FLOAT,
                zip NVARCHAR(20),
                CONSTRAINT PK_company_data PRIMARY KEY (symbol, date)
            );
        END;
    """
    db.execute_non_query(create_company_info)
    
    # Create table (StockData)
    create_stock_data = """
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'stock_data')
        BEGIN
            CREATE TABLE stock_data (
                date DATE NOT NULL,       
                symbol NVARCHAR(20) NOT NULL,   
                open_v FLOAT,
                high FLOAT,
                low FLOAT,
                close_v FLOAT,
                volume BIGINT,
                dividends FLOAT,
                stock_splits FLOAT,
                capital_gains FLOAT,      -- ✅ Nueva columna añadida
                CONSTRAINT PK_stock_data PRIMARY KEY (symbol, date)  
            );
        END;
    """
    db.execute_non_query(create_stock_data)
    
    # Create dividends data
    create_dividend_data = """
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dividend_data')
    BEGIN
        CREATE TABLE dividend_data (
        symbol NVARCHAR(20) NOT NULL,
        date DATE NOT NULL,  
        dividends FLOAT,
        CONSTRAINT Pk_dividend_data PRIMARY KEY (symbol, date)  
        );
    END
    """
    db.execute_non_query(create_dividend_data)
    
    # Create splits data 
    create_splits_data = """
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'split_data')
    BEGIN
        CREATE TABLE split_data (
        symbol NVARCHAR(20) NOT NULL,
        date DATE NOT NULL,  
        stock_splits FLOAT,
        CONSTRAINT Pk_split_data PRIMARY KEY (symbol, date)  
        );
    END
    """
    db.execute_non_query(create_splits_data)
    
    
    # Create cashflow data 
    create_cashflow_data = """
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'cashflow_data')
        BEGIN
            CREATE TABLE cashflow_data (
                symbol NVARCHAR(20) NOT NULL,
                date DATE NOT NULL,
                
                amortization_cash_flow FLOAT,
                amortization_of_intangibles FLOAT,
                amortization_of_securities FLOAT,
                asset_impairment_charge FLOAT,
                beginning_cash_position FLOAT,
                buy FLOAT,
                capital_expenditure FLOAT,
                capital_expenditure_reported FLOAT,
                cash_dividends_paid FLOAT,
                cash_flow_from_continuing_financing_activities FLOAT,
                cash_flow_from_continuing_investing_activities FLOAT,
                cash_flow_from_continuing_operating_activities FLOAT,
                cash_flow_from_discontinued_operation FLOAT,
                cash_flowsfromusedin_operating_activities_direct FLOAT,
                cash_from_discontinued_financing_activities FLOAT,
                cash_from_discontinued_investing_activities FLOAT,
                cash_from_discontinued_operating_activities FLOAT,
                change_in_account_payable FLOAT,
                change_in_accrued_expense FLOAT,
                change_in_dividend_payable FLOAT,
                change_in_income_tax_payable FLOAT,
                change_in_interest_payable FLOAT,
                change_in_inventory FLOAT,
                change_in_other_current_assets FLOAT,
                change_in_other_current_liabilities FLOAT,
                change_in_other_working_capital FLOAT,
                change_in_payable FLOAT,
                change_in_payables_and_accrued_expense FLOAT,
                change_in_prepaid_assets FLOAT,
                change_in_receivables FLOAT,
                change_in_tax_payable FLOAT,
                change_in_working_capital FLOAT,
                changes_in_account_receivables FLOAT,
                changes_in_cash FLOAT,
                classesof_cash_payments FLOAT,
                classesof_cash_receiptsfrom_operating_activities FLOAT,
                common_stock_dividend_paid FLOAT,
                common_stock_issuance FLOAT,
                common_stock_payments FLOAT,
                deferred_income_tax FLOAT,
                deferred_tax FLOAT,
                depletion FLOAT,
                depreciation FLOAT,
                depreciation_amortization_depletion FLOAT,
                depreciation_and_amortization FLOAT,
                dividend_paid_cfo FLOAT,
                dividend_received_cfo FLOAT,
                dividends_paid_direct FLOAT,
                dividends_received_cfi FLOAT,
                earnings_losses_from_equity_investments FLOAT,
                effect_of_exchange_rate_changes FLOAT,
                end_cash_position FLOAT,
                excess_tax_benefit_from_stock_based_compensation FLOAT,
                financing_cash_flow FLOAT,
                free_cash_flow FLOAT,
                gain_loss_on_investment_securities FLOAT,
                gain_loss_on_sale_of_business FLOAT,
                gain_loss_on_sale_of_ppe FLOAT,
                hold FLOAT,
                income_tax_paid_supplemental_data FLOAT,
                interest_paid_cff FLOAT,
                interest_paid_cfo FLOAT,
                interest_paid_direct FLOAT,
                interest_paid_supplemental_data FLOAT,
                interest_received_cfi FLOAT,
                interest_received_cfo FLOAT,
                interest_received_direct FLOAT,
                investing_cash_flow FLOAT,
                issuance_of_capital_stock FLOAT,
                issuance_of_debt FLOAT,
                long_term_debt_issuance FLOAT,
                long_term_debt_payments FLOAT,
                net_business_purchase_and_sale FLOAT,
                net_common_stock_issuance FLOAT,
                net_foreign_currency_exchange_gain_loss FLOAT,
                net_income_from_continuing_operations FLOAT,
                net_intangibles_purchase_and_sale FLOAT,
                net_investment_properties_purchase_and_sale FLOAT,
                net_investment_purchase_and_sale FLOAT,
                net_issuance_payments_of_debt FLOAT,
                net_long_term_debt_issuance FLOAT,
                net_other_financing_charges FLOAT,
                net_other_investing_changes FLOAT,
                net_ppe_purchase_and_sale FLOAT,
                net_preferred_stock_issuance FLOAT,
                net_short_term_debt_issuance FLOAT,
                operating_cash_flow FLOAT,
                operating_gains_losses FLOAT,
                other_cash_adjustment_inside_changein_cash FLOAT,
                other_cash_adjustment_outside_changein_cash FLOAT,
                other_cash_paymentsfrom_operating_activities FLOAT,
                other_cash_receiptsfrom_operating_activities FLOAT,
                other_non_cash_items FLOAT,
                paymentson_behalfof_employees FLOAT,
                paymentsto_suppliersfor_goodsand_services FLOAT,
                pension_and_employee_benefit_expense FLOAT,
                period NVARCHAR(20),
                preferred_stock_dividend_paid FLOAT,
                preferred_stock_issuance FLOAT,
                preferred_stock_payments FLOAT,
                proceeds_from_stock_option_exercised FLOAT,
                provisionand_write_offof_assets FLOAT,
                purchase_of_business FLOAT,
                purchase_of_intangibles FLOAT,
                purchase_of_investment FLOAT,
                purchase_of_investment_properties FLOAT,
                purchase_of_ppe FLOAT,
                repayment_of_debt FLOAT,
                repurchase_of_capital_stock FLOAT,
                sale_of_business FLOAT,
                sale_of_intangibles FLOAT,
                sale_of_investment FLOAT,
                sale_of_investment_properties FLOAT,
                sale_of_ppe FLOAT,
                sell FLOAT,
                short_term_debt_issuance FLOAT,
                short_term_debt_payments FLOAT,
                stock_based_compensation FLOAT,
                strongbuy FLOAT,
                strongsell FLOAT,
                taxes_refund_paid FLOAT,
                unrealized_gain_loss_on_investment_securities FLOAT,

                -- ✅ Clave primaria
                CONSTRAINT pk_cashflow_data PRIMARY KEY (symbol, date)
            );

        END;
        """

    db.execute_non_query(create_cashflow_data)
    
    # Create recommendations data 
    create_recommendations_data="""
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'recommendations_data')
    BEGIN
        CREATE TABLE recommendations_data (
            symbol NVARCHAR(20) NOT NULL,
            date DATE NOT NULL,
            period NVARCHAR(10) NOT NULL,
            strongbuy INT,
            buy INT,
            hold INT,
            sell INT,
            strongsell INT,
            CONSTRAINT pk_recommendations PRIMARY KEY (symbol, date, period)
        );
    END;
    """
    db.execute_non_query(create_recommendations_data)
    
    
    # Create balances data  balance_data
    create_balance_data="""
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'balance_sheet_data')
        BEGIN
            CREATE TABLE balance_sheet_data (
                symbol NVARCHAR(20) NOT NULL,
                date DATE NOT NULL,
                accounts_payable FLOAT,
                accounts_receivable FLOAT,
                accrued_interest_receivable FLOAT,
                accumulated_depreciation FLOAT,
                additional_paid_in_capital FLOAT,
                allowance_for_doubtful_accounts_receivable FLOAT,
                assets_held_for_sale_current FLOAT,
                available_for_sale_securities FLOAT,
                buildings_and_improvements FLOAT,
                capital_lease_obligations FLOAT,
                capital_stock FLOAT,
                cash_and_cash_equivalents FLOAT,
                cash_cash_equivalents_and_federal_funds_sold FLOAT,
                cash_cash_equivalents_and_short_term_investments FLOAT,
                cash_equivalents FLOAT,
                cash_financial FLOAT,
                commercial_paper FLOAT,
                common_stock FLOAT,
                common_stock_equity FLOAT,
                construction_in_progress FLOAT,
                current_accrued_expenses FLOAT,
                current_assets FLOAT,
                current_capital_lease_obligation FLOAT,
                current_debt FLOAT,
                current_debt_and_capital_lease_obligation FLOAT,
                current_deferred_assets FLOAT,
                current_deferred_liabilities FLOAT,
                current_deferred_revenue FLOAT,
                current_deferred_taxes_assets FLOAT,
                current_deferred_taxes_liabilities FLOAT,
                current_liabilities FLOAT,
                current_notes_payable FLOAT,
                current_provisions FLOAT,
                defined_pension_benefit FLOAT,
                derivative_product_liabilities FLOAT,
                dividends_payable FLOAT,
                duefrom_related_parties_current FLOAT,
                duefrom_related_parties_non_current FLOAT,
                dueto_related_parties_current FLOAT,
                dueto_related_parties_non_current FLOAT,
                employee_benefits FLOAT,
                financial_assets FLOAT,
                financial_assets_designatedas_fair_value_through_profitor_loss_total FLOAT,
                finished_goods FLOAT,
                foreign_currency_translation_adjustments FLOAT,
                gains_losses_not_affecting_retained_earnings FLOAT,
                general_partnership_capital FLOAT,
                goodwill FLOAT,
                goodwill_and_other_intangible_assets FLOAT,
                gross_accounts_receivable FLOAT,
                gross_ppe FLOAT,
                hedging_assets_current FLOAT,
                held_to_maturity_securities FLOAT,
                income_tax_payable FLOAT,
                interest_payable FLOAT,
                inventories_adjustments_allowances FLOAT,
                inventory FLOAT,
                invested_capital FLOAT,
                investment_properties FLOAT,
                investmentin_financial_assets FLOAT,
                investments_and_advances FLOAT,
                investments_in_other_ventures_under_equity_method FLOAT,
                investmentsin_associatesat_cost FLOAT,
                investmentsin_joint_venturesat_cost FLOAT,
                investmentsin_subsidiariesat_cost FLOAT,
                land_and_improvements FLOAT,
                leases FLOAT,
                liabilities_heldfor_sale_non_current FLOAT,
                limited_partnership_capital FLOAT,
                line_of_credit FLOAT,
                loans_receivable FLOAT,
                long_term_capital_lease_obligation FLOAT,
                long_term_debt FLOAT,
                long_term_debt_and_capital_lease_obligation FLOAT,
                long_term_equity_investment FLOAT,
                long_term_provisions FLOAT,
                machinery_furniture_equipment FLOAT,
                minimum_pension_liabilities FLOAT,
                minority_interest FLOAT,
                net_debt FLOAT,
                net_ppe FLOAT,
                net_tangible_assets FLOAT,
                non_current_accounts_receivable FLOAT,
                non_current_accrued_expenses FLOAT,
                non_current_deferred_assets FLOAT,
                non_current_deferred_liabilities FLOAT,
                non_current_deferred_revenue FLOAT,
                non_current_deferred_taxes_assets FLOAT,
                non_current_deferred_taxes_liabilities FLOAT,
                non_current_note_receivables FLOAT,
                non_current_pension_and_other_postretirement_benefit_plans FLOAT,
                non_current_prepaid_assets FLOAT,
                notes_receivable FLOAT,
                ordinary_shares_number FLOAT,
                other_current_assets FLOAT,
                other_current_borrowings FLOAT,
                other_current_liabilities FLOAT,
                other_equity_adjustments FLOAT,
                other_equity_interest FLOAT,
                other_intangible_assets FLOAT,
                other_inventories FLOAT,
                other_investments FLOAT,
                other_non_current_assets FLOAT,
                other_non_current_liabilities FLOAT,
                other_payable FLOAT,
                other_properties FLOAT,
                other_receivables FLOAT,
                other_short_term_investments FLOAT,
                payables FLOAT,
                payables_and_accrued_expenses FLOAT,
                pensionand_other_post_retirement_benefit_plans_current FLOAT,
                preferred_securities_outside_stock_equity FLOAT,
                preferred_shares_number FLOAT,
                preferred_stock FLOAT,
                preferred_stock_equity FLOAT,
                prepaid_assets FLOAT,
                properties FLOAT,
                raw_materials FLOAT,
                receivables FLOAT,
                receivables_adjustments_allowances FLOAT,
                restricted_cash FLOAT,
                restricted_common_stock FLOAT,
                retained_earnings FLOAT,
                share_issued FLOAT,
                stockholders_equity FLOAT,
                tangible_book_value FLOAT,
                taxes_receivable FLOAT,
                total_assets FLOAT,
                total_capitalization FLOAT,
                total_debt FLOAT,
                total_equity_gross_minority_interest FLOAT,
                total_liabilities_net_minority_interest FLOAT,
                total_non_current_assets FLOAT,
                total_non_current_liabilities_net_minority_interest FLOAT,
                total_partnership_capital FLOAT,
                total_tax_payable FLOAT,
                tradeand_other_payables_non_current FLOAT,
                trading_securities FLOAT,
                treasury_shares_number FLOAT,
                treasury_stock FLOAT,
                unrealized_gain_loss FLOAT,
                work_in_process FLOAT,
                working_capital FLOAT,
                fixed_assets_revaluation_reserve NVARCHAR(50),
                CONSTRAINT pk_balance_sheet_data PRIMARY KEY (symbol, date)
            );
        END;
    """
    db.execute_non_query(create_balance_data)
    
    # Create finance data  finance_data
    create_finance_data="""
        IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'financial_data')
            BEGIN
                CREATE TABLE financial_data (
                    symbol NVARCHAR(20) NOT NULL,
                    date DATE NOT NULL,
                    amortization FLOAT,
                    amortization_of_intangibles_income_statement FLOAT,
                    average_dilution_earnings FLOAT,
                    basic_average_shares FLOAT,
                    basic_eps FLOAT,
                    cost_of_revenue FLOAT,
                    depreciation_amortization_depletion_income_statement FLOAT,
                    depreciation_and_amortization_in_income_statement FLOAT,
                    depreciation_income_statement FLOAT,
                    diluted_average_shares FLOAT,
                    diluted_eps FLOAT,
                    diluted_ni_availto_com_stockholders FLOAT,
                    earnings_from_equity_interest FLOAT,
                    earnings_from_equity_interest_net_of_tax FLOAT,
                    ebit FLOAT,
                    ebitda FLOAT,
                    gain_on_sale_of_business FLOAT,
                    gain_on_sale_of_ppe FLOAT,
                    gain_on_sale_of_security FLOAT,
                    general_and_administrative_expense FLOAT,
                    gross_profit FLOAT,
                    impairment_of_capital_assets FLOAT,
                    insurance_and_claims FLOAT,
                    interest_expense FLOAT,
                    interest_expense_non_operating FLOAT,
                    interest_income FLOAT,
                    interest_income_non_operating FLOAT,
                    loss_adjustment_expense FLOAT,
                    minority_interests FLOAT,
                    net_income FLOAT,
                    net_income_common_stockholders FLOAT,
                    net_income_continuous_operations FLOAT,
                    net_income_discontinuous_operations FLOAT,
                    net_income_from_continuing_and_discontinued_operation FLOAT,
                    net_income_from_continuing_operation_net_minority_interest FLOAT,
                    net_income_from_tax_loss_carryforward FLOAT,
                    net_income_including_noncontrolling_interests FLOAT,
                    net_interest_income FLOAT,
                    net_non_operating_interest_income_expense FLOAT,
                    net_policyholder_benefits_and_claims FLOAT,
                    normalized_ebitda FLOAT,
                    normalized_income FLOAT,
                    occupancy_and_equipment FLOAT,
                    operating_expense FLOAT,
                    operating_income FLOAT,
                    operating_revenue FLOAT,
                    other_gand_a FLOAT,
                    other_income_expense FLOAT,
                    other_non_interest_expense FLOAT,
                    other_non_operating_income_expenses FLOAT,
                    other_operating_expenses FLOAT,
                    other_special_charges FLOAT,
                    other_taxes FLOAT,
                    otherunder_preferred_stock_dividend FLOAT,
                    policyholder_benefits_ceded FLOAT,
                    policyholder_benefits_gross FLOAT,
                    preferred_stock_dividends FLOAT,
                    pretax_income FLOAT,
                    professional_expense_and_contract_services_expense FLOAT,
                    provision_for_doubtful_accounts FLOAT,
                    reconciled_cost_of_revenue FLOAT,
                    reconciled_depreciation FLOAT,
                    rent_and_landing_fees FLOAT,
                    rent_expense_supplemental FLOAT,
                    research_and_development FLOAT,
                    restructuring_and_mergern_acquisition FLOAT,
                    salaries_and_wages FLOAT,
                    securities_amortization FLOAT,
                    selling_and_marketing_expense FLOAT,
                    selling_general_and_administration FLOAT,
                    special_income_charges FLOAT,
                    tax_effect_of_unusual_items FLOAT,
                    tax_provision FLOAT,
                    tax_rate_for_calcs FLOAT,
                    total_expenses FLOAT,
                    total_operating_income_as_reported FLOAT,
                    total_other_finance_cost FLOAT,
                    total_revenue FLOAT,
                    total_unusual_items FLOAT,
                    total_unusual_items_excluding_goodwill FLOAT,
                    write_off FLOAT,
                    net_income_extraordinary NVARCHAR(50),
                    CONSTRAINT pk_financial_data PRIMARY KEY (symbol, date)
                );
            END;
    """
    db.execute_non_query(create_finance_data)
    
    return











def main():
    db = Database('pre')
    db.connect()
    create_tables(db)
    db.close()


if __name__ == "__main__":
    main()